# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Libretro.RetroArch
PackageVersion: 1.10.3.0
PackageLocale: en-US
Publisher: Libretro
PackageName: RetroArch
License: mit license
Copyright: The Libretro Team, 2010-2021
ShortDescription: RetroArch is a frontend for emulators, game engines and media players
ManifestType: defaultLocale
ManifestVersion: 1.1.0

