# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Libretro.RetroArch
PackageVersion: 1.10.3.0
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://buildbot.libretro.com/stable/1.10.3/windows/x86_64/RetroArch-Win64-setup.exe
  InstallerSha256: 563CA2FE3C9352B5DBE061AE5876815BBA8CD5A098BC217CEC1EE4E2E9EB94BF
ManifestType: installer
ManifestVersion: 1.1.0

